name: jet
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pip=24.3.1
  - numpy=1.24.4
  - pillow            # OLED 렌더링
  - pyserial=3.5
  - pyusb=1.2.1
  - pyftdi=0.55.4
  - traitlets=5.14.3
  - typing_extensions=4.12.2
  - sysv_ipc=1.1.0
  - toml=0.10.2
  - setuptools=75.3.0
  - wheel=0.45.1
  - pip:
      # Adafruit / Jetson 관련 (네 버전 목록 기준으로 고정)
      - Adafruit-Blinka==8.64.0
      - Adafruit-PlatformDetect==3.82.0
      - Adafruit-PureIO==1.1.11
      - adafruit-circuitpython-busdevice==5.2.13
      - adafruit-circuitpython-connectionmanager==3.1.5
      - adafruit-circuitpython-typing==1.12.1
      - adafruit-circuitpython-requests==4.1.13
      # 디바이스 드라이버
      - adafruit-circuitpython-ina219
      - adafruit-circuitpython-ssd1306==2.12.21   # (CircuitPython용 ssd1306)
      - Adafruit-SSD1306                           # (네가 쓰는 레거시 드라이버)
      - adafruit-circuitpython-pca9685==3.4.19
      - adafruit-circuitpython-servokit==1.3.21
      - adafruit-circuitpython-motor==3.4.17
      - Jetson.GPIO==2.1.9
      - smbus2==0.5.0

